version: "3"
services:
  web:
    container_name: paragon_web
    build: .
    command: npm run dev
    depends_on:
      - db
    volumes:
      - ./:/app
      - /node_modules
  
  db:
    container_name: paragon_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --
    restart: unless-stopped
    volumes:
      - ./src/data/db_init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ~/wearenv/paragon/docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: paragon
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: paragon
      MYSQL_PASSWORD: paragon
      SERVICE_TAG: dev
      SERVICE_NAME: paragon_db
    networks:
      - paragon_net

    # volumes:
  
  phpmyadmin:
    container_name: sql_admin
    image: phpmyadmin:5.2.0-apache
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"


networks:
  paragon_net:
    driver: bridge
