version: "3"

volumes:
  mysql-data:
    

services:
  web:
    container_name: paragon_web
    build: .
    command: npm run
    depends_on:
      - db
    volumes:
      - ./:/app
      - /node_modules
    networks:
      - paragon_net 
    ports:
      - "3030:3030"
  
  db:
    container_name: paragon_db
    image: mysql:8.0
    command: 
      --default-authentication-plugin=mysql_native_password
      --init-file ./src/data/db_init.sql
    restart: unless-stopped
    volumes:
      - ./src/data/db_init.sql:/docker-entrypoint-initdb.d/
      - mysql-data:/var/lib/mysql
    ports:
      - "3360:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: paragon
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: paragon99
      SERVICE_TAG: dev
      SERVICE_NAME: paragon_db
    networks:
      - paragon_net

    # volumes:
  
  phpmyadmin:
    container_name: sql_admin
    image: phpmyadmin:5.2.0-apache
    restart: always
    depends_on:
      - db
    ports:
      - "8090:80"

    networks:
      - paragon_net


networks:
  paragon_net:
    driver: bridge
